Documentation:
  # Skips checking to make sure top level modules / classes have a comment.
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 25

Metrics/LineLength:
  Max: 100

Style/ClassAndModuleChildren:
  # Skips checking the style of children definitions at classes and modules.
  #
  # Basically there are two different styles:
  #
  # `nested` - have each child on a separate line
  #   class Foo
  #     class Bar
  #     end
  #   end
  #
  # `compact` - combine definitions as much as possible
  #   class Foo::Bar
  #   end
  #
  # With it disabled, either or is valid.
  Enabled: false
